env_files = ["./robot.env"]

[env]
DEST_DIR = "~/robot"

[env.development]
BIN_PATH = "target/armv7-unknown-linux-gnueabihf/debug/robot"

[env.release]
# TODO make this actually do a release build
BIN_PATH = "target/armv7-unknown-linux-gnueabihf/release/robot"

[tasks.ssh]
args = ["${ROBOT_HOST}", "${@}"]
command = "ssh"

[tasks.mkdir]
args = ["${ROBOT_HOST}", "mkdir -p ${DEST_DIR}"]
command = "ssh"

[tasks.deploy]
dependencies = ["build", "mkdir"]
script = ["rsync -r ${BIN_PATH} config ${ROBOT_HOST}:${DEST_DIR}/./"]

[tasks.fmt]
# Formatting requires nightly for experimental settings
args = ["+nightly", "fmt"]
command = "cargo"
